package model;
// Generated Dec 2, 2025 9:31:21 AM by Hibernate Tools 4.3.1

import javax.persistence.*;
import java.io.Serializable;

@Entity
@Table(name = "karyawan")

/**
 * Karyawan generated by hbm2java
 */
public class Karyawan  implements java.io.Serializable {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    
    @Column(name = "id")
    private Integer id;
    
    @Column(name = "nik") // Nomor Induk Karyawan
    private String nik;
    
    @Column(name = "nama")
    private String nama;
    
    @Column(name = "jabatan") // Jabatan
    private String jabatan;

     
    public Karyawan() {
    }

    public Karyawan(String nik, String nama, String jabatan) {
       this.nik = nik;
       this.nama = nama;
       this.jabatan = jabatan;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNik() {
        return this.nik;
    }
    
    public void setNik(String nik) {
        this.nik = nik;
    }
    public String getNama() {
        return this.nama;
    }
    
    public void setNama(String nama) {
        this.nama = nama;
    }
    public String getJabatan() {
        return this.jabatan;
    }
    
    public void setJabatan(String jabatan) {
        this.jabatan = jabatan;
    }
    
    @Override
    public String toString() {
        return "Karyawan{" + 
            "id=" + id +
            ", nik='" + nik + '\'' +
            ", nama='" + nama + '\'' +
            ", jabatan='" + jabatan + '\'' +
            '}';
    }
}


